# -*- coding: utf-8 -*-
"""BNCT 分組英文版 — 批次 b：thor / accelerator / headneck / gbm
中文定稿見 zhsrc/<slug>.html。引用連結 HTML 逐字照抄中文，順序與重複位置相同；
<h4> 數量與順序、<p> 段落數也與中文一致。
兩則警語、排擠句、利益揭露、查證日期、參考清單由建置程式加上（見 parts_en.py）。
"""

EN = {}

# ---------------------------------------------------------------- B7 thor
EN["thor"] = dict(
 title="Taiwan's neutron source is on a campus, not in a hospital",
 dek="It is a research reactor, not a hospital treatment machine, and that single fact shapes both of the routes Taiwan currently has.",
 lead="This is the one article in the section that describes what Taiwan actually has today. I have put the figures from the official pages in one place, including the ones that are easiest to misread.",
 body="""<p>Taiwan's BNCT neutron source is the pool-type research reactor at National Tsing Hua University, known as THOR. It is on a university campus, not inside a hospital: patients are taken there to be irradiated, and go back to their own hospital afterwards.</p>

<h4>Two routes, and they are nothing alike</h4>
<p>The first route is academic clinical trials. Those currently listed on the official pages are these<a href="https://thor.site.nthu.edu.tw/p/403-1192-11030-1.php?Lang=zh-tw" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>: head and neck cancer, phase 1, opened in January 2026, with 2 patients enrolled as of August 2026 against a planned 16 treatment sessions; brain tumours, phase 1, opened in January 2024, with 17 patients enrolled against a planned 55 treatment sessions<a href="https://thor.site.nthu.edu.tw/p/406-1192-278369,r11030.php?Lang=zh-tw" target="_blank" rel="noopener"><sup class="cit">[2]</sup></a>; and liver cancer, phase 1, <strong>still under application and not yet enrolling</strong>. There is also one completed phase 2 trial in head and neck cancer, 14 patients, 2014 to 2021<a href="https://thor.site.nthu.edu.tw/p/406-1192-278368,r11030.php?Lang=zh-tw" target="_blank" rel="noopener"><sup class="cit">[3]</sup></a>.</p>
<p>The second route is what the official pages call emergency treatment, with a doctor at a collaborating hospital assessing the patient and referring them across. Since January 2017 it has accumulated 629 treatment sessions: 402 for brain tumours, 207 for head and neck cancer, and 20 for everything else<a href="https://thor.site.nthu.edu.tw/p/406-1192-278370,r11030.php?Lang=zh-tw" target="_blank" rel="noopener"><sup class="cit">[4]</sup></a>. The cancers behind those other 20 sessions are listed on the official page as liver cancer, melanoma and breast cancer.</p>
<p>An important sentence has to follow here: <strong>a cancer appearing in this tally does not mean that cancer has evidence behind it.</strong> This route deals with how urgent one person's situation is, not with a judgement about whether the treatment works. The fourteenth article explains that the human data for deep organs currently amounts to single-digit numbers of case reports. Before taking this route, the depth question in the third article and the four conditions in the seventeenth have to be worked through first, just the same.</p>

<h4>The same patient treated twice counts twice</h4>
<p>This distinction matters enough to be given a section of its own. The unit used on the official pages is the <strong>treatment session</strong>: one patient irradiated twice counts as two. A compilation by an international society uses a patient count instead, and puts it at close to 500<a href="https://isnct.net/clinical-centres-in-taiwan/" target="_blank" rel="noopener"><sup class="cit">[5]</sup></a>. The two figures are in different units. You cannot use one to check the other, and you cannot divide one by the other and get a rate out of it.</p>
<p>The same applies to the response rate that gets quoted from here now and then: it comes from the referral-route statistics, pooled across cancers and counted in treatment sessions, not from a prospective trial. <strong>It is not the same kind of thing as the trial figures in the ninth and tenth articles.</strong></p>

<h4>The licence granted in 2023, and which kind of licence it is</h4>
<p>In June 2023 the "NTHU neutron radiation irradiation system" was granted a medical device licence by the Ministry of Health and Welfare<a href="https://www.nthu.edu.tw/hotNews/content/1141" target="_blank" rel="noopener"><sup class="cit">[6]</sup></a>. This is often written up as BNCT having been approved in Taiwan. Those are two different things.</p>
<p><strong>It is a licence for a device. It is not a licence for the treatment, and it is not a drug approval.</strong> The sixteenth article is about that distinction from end to end, and it also explains why this referral route is so hard to give a regulatory name to at all.</p>

<h4>On cost, the figure to ask for is not the one on the schedule</h4>
<p>THOR publishes a fee schedule, but what that schedule covers is <strong>the reactor side of the treatment</strong>: beam quality assurance, running the reactor, treatment planning, positioning, analysis of blood boron concentration, dose monitoring, and measurement of surface radiation after the irradiation.</p>
<p>The boron drug, the inpatient stay, the travelling, and the clinical charges raised by the collaborating hospital are all outside it. So what you actually need to get hold of is the total for the whole journey, not the single figure on the published schedule. It is not a National Health Insurance item, and it is not a routine self-pay item you can obtain by registering at a clinic.</p>""",
)

# --------------------------------------------------------- B8 accelerator
EN["accelerator"] = dict(
 title="Swapping the reactor for an accelerator changes less than it sounds",
 dek="You no longer need a nuclear reactor to make the neutrons, which is the largest change BNCT has had in a decade. What it changed is access, not effect.",
 lead="Accelerator-based BNCT is usually described as the next generation. It is a genuine step, but the step goes in a different direction from the one most people assume.",
 body="""<p>BNCT was stuck for decades, and the hardest barrier was never the biology. It was where the neutrons come from. Building a nuclear reactor inside a hospital is not realistic, so the treatment stayed tethered to research institutions.</p>

<h4>How it is done: fire protons at a beryllium target</h4>
<p>The accelerator approach is to accelerate protons up to a given energy, drive them into a target material such as beryllium to knock neutrons out of it, and then shape those neutrons through a moderator into an epithermal beam suitable for treatment.</p>
<p>In March 2020 Japan's Ministry of Health, Labour and Welfare approved an accelerator-based BNCT system made by Sumitomo Heavy Industries, together with its dose calculation programme, described as the first BNCT system anywhere to be granted medical device status<a href="https://www.shi.co.jp/english/info/2019/6kgpsq0000002ji0.html" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. That system uses a 30 MeV proton cyclotron and a beryllium target.</p>
<p>This machine is the device the fourth article refers to: the drug approval and the device approval are the two halves of a single approval.</p>

<h4>What giving up the reactor actually buys</h4>
<p>It buys three things: <strong>access, a lower barrier to building one, and scheduling.</strong> An accelerator can be built on a hospital campus without the whole apparatus of regulation and operating conditions that a nuclear reactor demands. For whether a treatment can grow at all, that is decisive.</p>
<p>The list of what it did not change is longer. The boron is the same boron, and the order of magnitude of the selectivity has not moved (fourth article); neutron attenuation in tissue has not changed, so the depth limit is exactly what it was (third article); there are still four dose components (second article). <strong>"Accelerator-based" is not an adjective about how well the treatment works; it describes where the neutrons came from.</strong> When a promotional page puts "accelerator" and "better" into the same sentence, two separate things have been joined at the seam.</p>

<h4>Machines that share the name still differ from each other</h4>
<p>Among the accelerators already treating patients, proton energies run from a few MeV up to thirty, and the target materials and moderator designs differ as well. Those differences show up in the energy spectrum of the beam, in its dose rate, and in the depth it can treat, which is to say in the shape of the attenuation curve from the third article.</p>
<p>The awkward part, from where the patient is sitting, is this: <strong>these specifications are almost impossible to obtain, and there is no public comparison across machine types.</strong> So the phrase "accelerator-based" carries no information about efficacy at all. What is worth asking is still the pair of questions from the third and fifth articles: how much dose can my lesion receive at that depth, and does the boron get into it.</p>

<h4>Where the world has actually reached</h4>
<p>Japan is the only place that has approved both the drug and the machine and brought them into its insurance system. Europe's first case took place in Helsinki in June 2025<a href="https://www.raysearchlabs.com/media/press-releases/2025/raystation-used-for-pioneering-clinical-milestone-at-helsinki-university-hospital--first-treatment-with-accelerator-based-bnct-in-europe/" target="_blank" rel="noopener"><sup class="cit">[2]</sup></a>, and that was a trial, not routine treatment. The regulatory detail belongs to the sixteenth article.</p>
<p>Tsukuba University in Japan is following a separate route with a linear accelerator using 8 MeV protons, currently running a phase 1 trial in newly diagnosed glioblastoma. <strong>The paper published on that trial is the study protocol, and it has reported no efficacy results of any kind</strong>; the enrolment target is 12 to 18 patients, and the eleventh article returns to it.</p>
<p>What this section is for is a sense of time: <strong>moving neutrons into hospitals is something the world has only been doing for a few years.</strong> Accelerators let more hospitals afford the machine. They have not made the numbers in any paper look better.</p>""",
)

# ----------------------------------------------------------- B9 headneck
EN["headneck"] = dict(
 title="The one approved indication rests on twenty-one patients",
 dek="This is the strongest square BNCT has, and strongest here means one single-arm trial of 21 people, which this article takes apart patient by patient.",
 lead="Japan's approval was built on this square, and Taiwan's trials cluster here too. By the end you will know how much this evidence weighs, and also how little.",
 body="""<p>The evidence level goes at the top, before anything else: <strong>a single-arm phase 2 trial, plus one real-world post-marketing surveillance study, and no randomisation anywhere.</strong></p>

<h4>Japan's JHN002: twenty-one people</h4>
<p>This was an open-label, single-arm phase 2 trial with no control group<a href="https://doi.org/10.1016/j.radonc.2020.11.001" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. It enrolled 21 patients in two cohorts: 8 with recurrent squamous cell carcinoma, and 13 with recurrent or locally advanced non-squamous carcinoma. The beam was an epithermal neutron beam from a cyclotron; the boron drug was borofalan (10B), at 400 mg per kilogram.</p>
<p>The primary endpoint was objective response rate, and it came out at 71% overall. Split apart: among the 8 squamous patients, 50% had a complete response and 25% a partial response; among the 13 non-squamous patients, 8% had a complete response and 62% a partial response. Two-year overall survival was 58% in the squamous group and 100% in the non-squamous group. Median locoregional progression-free survival in the squamous group was 11.5 months<a href="https://doi.org/10.1016/j.radonc.2020.11.001" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>.</p>
<p><strong>Two things need saying plainly.</strong> First, the denominator behind "100% two-year survival in the non-squamous group" is 13 people. The figure is beautiful to look at, and a number built on 13 people can only be known within wide limits; the confidence interval would show you how wide, and the abstract does not give it. Second, this trial <strong>did not report a median overall survival</strong>. I went through the original abstract, the review documents and the later sub-analysis, and it is not in any of them. So any sentence of the form "JHN002 showed a median survival of so many months" is not coming from this trial, whichever page it is printed on, and it is worth asking where it did come from.</p>

<h4>The side effects are not small</h4>
<p>Alopecia 95%, hyperamylasaemia 86%, nausea 81%<a href="https://doi.org/10.1016/j.radonc.2020.11.001" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. In the sub-analysis, the grade 3 or higher events include hyperamylasaemia at 76%, of which grade 4 accounted for 71%<a href="https://academic.oup.com/jrr/article/63/3/393/6564355" target="_blank" rel="noopener"><sup class="cit">[2]</sup></a>. Those are not rates you would associate with a treatment described as gentle, and they come from the trial the approval was built on.</p>
<p>In passing: some second-hand write-ups state that this trial had no grade 4 toxicity, which does not reconcile with the sub-analysis. The fifteenth article handles that in full.</p>

<h4>The real-world 162</h4>
<p>After approval, Japan ran a nationwide post-marketing surveillance study: 162 patients with complete safety data, of whom 144 had recurrent squamous cell carcinoma of the head and neck<a href="https://www.mdpi.com/2072-6694/16/5/869" target="_blank" rel="noopener"><sup class="cit">[3]</sup></a>. Within those 144 squamous patients, the objective response rate was 72.3% (complete response 46.0%, partial response 26.3%), and one-year and two-year overall survival were 78.8% and 60.7%.</p>
<p><strong>This is not a way of checking the 71%.</strong> JHN002's 71% was calculated across all 21 patients, squamous and non-squamous together, while the 72.3% is calculated within the 144 squamous patients only. The two percentages do not share a denominator, and setting them side by side implies an agreement that was never tested. What the surveillance is genuinely worth is something narrower and still useful: with a much larger denominator, and in ordinary practice rather than trial conditions, the response rate stayed in the same order of magnitude. It cannot stand in for a control group, and it does not turn 71% into a verified number.</p>

<h4>Taiwan's two trials, and why the figures must not be mixed</h4>
<p>The reactor at Tsing Hua has run two different trials, and they are routinely cited as though they were one. Keeping them apart is the whole point of this section.</p>
<p>The first delivered BNCT in two fractions: 17 patients, 23 recurrent lesions, <strong>single-arm, single-centre, no control group</strong> (the phase is not stated in any source I can verify, so I am not going to supply one). Six patients had a complete response and six a partial response; <strong>two-year locoregional control was 28% and two-year overall survival 47%</strong>; median follow-up was 19.9 months<a href="https://link.springer.com/article/10.1186/s40880-018-0295-y" target="_blank" rel="noopener"><sup class="cit">[4]</sup></a>.</p>
<p>The second was a phase 1/2 trial in which a single BNCT session was followed by image-guided intensity-modulated radiotherapy: 14 patients enrolled and 12 completed, and this is the completed trial referred to in the seventh article. Five patients had a complete response and four a partial response; <strong>one-year overall survival was 56% and one-year local progression-free survival 21%</strong>; median follow-up was 11.8 months<a href="https://www.mdpi.com/2072-6694/15/10/2762" target="_blank" rel="noopener"><sup class="cit">[5]</sup></a>. <strong>This trial reported only one-year figures and has no two-year numbers</strong>, so when you see a two-year survival rate attributed to it, that is a misquotation. Different treatment schedules, different sizes, different follow-up lengths: the only safe habit is to name which of the two you mean every time you quote either.</p>

<h4>Reading the 47% correctly</h4>
<p>Everyone in this square has already been irradiated once, has recurred, and is not a candidate for surgery or chemotherapy. That is the starting point, and it is worth holding onto while reading what follows. The Taiwanese trial (17 patients, single arm, no control group) had two-year survival of 47%. But for BNCT in advanced or recurrent head and neck cancer, a Japanese prospective series of 62 patients reported a median survival of 10.1 months and two-year survival of 24.2%<a href="https://academic.oup.com/jrr/article/55/1/146/917082" target="_blank" rel="noopener"><sup class="cit">[6]</sup></a>.</p>
<p><strong>The two figures differ by almost a factor of two, and both come from single arms.</strong> That gap is itself the demonstration. With no control group, the number moves a long way depending on who happened to be enrolled: how far the disease had gone, how well the patients were, how large the lesions were, how long anyone was followed. So the claim that stands up is not "half of them are still alive at two years". It is <strong>"some people in this square do get past two years, and what proportion has not yet been reliably measured"</strong>. That is a weaker sentence, and it is the one the data actually pays for.</p>
<p>Hold this alongside it. Local response rate is about the tumour getting smaller; two-year survival is about the person still being here; and in this group the two come apart badly. Two-year local control in the Taiwanese trial was only 28%, while overall survival was 47%. <strong>For most of them, the tumour came back in the end.</strong> That is an unpleasant sentence to write out, and it is what it takes to put the expectation where it belongs before treatment rather than after.</p>""",
)

# ---------------------------------------------------------------- B10 gbm
EN["gbm"] = dict(
 title="The scans showed no shrinkage, yet they lived longer",
 dek="This trial's imaging response rate was 3.7%, and the same patients had a median survival of 18.9 months. Both are true, and neither had a control group.",
 lead="This is the longest and the most important article in the section. On the surface it is about brain tumours; underneath, it is about how to judge a trial that has no control group. Learn this once and the same move will not work on you again.",
 body="""<p>The evidence level here has to be written in two layers: <strong>the trial itself is single-arm phase 2, and its survival comparison is made against a historical cohort.</strong> That second layer is what this article is really about.</p>

<h4>The JG002 numbers</h4>
<p>This was a Japanese multicentre, open-label, single-arm phase 2 trial. It enrolled 27 patients, of whom 24 had recurrent glioblastoma, recruiting between 2016 and 2018<a href="https://academic.oup.com/noa/article/3/1/vdab067/6279119" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. It used a cyclotron-based epithermal neutron source, with the boron drug given at 500 mg per kilogram. The primary endpoint was one-year survival in recurrent glioblastoma.</p>
<p>The result: <strong>one-year survival was 79.2% (95% confidence interval 57.0 to 90.8), and median overall survival was 18.9 months.</strong></p>
<p>The same report carries two other numbers: <strong>the imaging response rate read by RANO was 3.7% across all 27 patients, which is one partial response; and median progression-free survival was 0.9 months.</strong></p>
<p>Nought point nine months. Which is to say that on imaging almost every patient had "progressed" inside a month, and a year later nearly eight in ten of them were still alive. Those two statements sit in the same paper, about the same 27 people. Neither is a misprint, and the work of this article is to explain how both can be true at once.</p>

<h4>First thing: imaging and survival can come apart</h4>
<p>After the brain has been irradiated there is a phenomenon that turns up often. The tumour looks larger on the scan and takes up contrast more avidly, but what is actually happening is inflammation and a change in the blood-brain barrier caused by the treatment, not tumour growth. It is called pseudoprogression. The RANO criteria, which are the standard way of reading these scans, will score it as progression, because from the outside it looks like progression.</p>
<p>So in the first months after BNCT, imaging is not a reliable thing to read. <strong>The 0.9 months of progression-free survival mainly reflects a reading standard failing in this particular situation, rather than a treatment that stopped working within a month.</strong></p>
<p>This has a practical use in clinic. If you or someone in your family is having this kind of treatment and the first scan report afterwards says progression, do not take it as settled. Ask the doctor whether this could be pseudoprogression, and whether it is worth repeating the scan before any decision is made on the strength of it.</p>

<h4>Second thing: the 18.9 months, compared against whom</h4>
<p>JG002 had no control group, so its authors took another trial as the comparator: JO22506, a single-arm phase 2 trial published in 2012, treating recurrent malignant glioma with bevacizumab alone, 31 patients, median overall survival 10.5 months<a href="https://academic.oup.com/jjco/article/42/10/887/814954" target="_blank" rel="noopener"><sup class="cit">[2]</sup></a>. Set 18.9 against 10.5 and it looks like a large gap.</p>
<p>The authors explained why they considered the comparison permissible: both trials enrolled bevacizumab-naive recurrent glioblastoma, so the populations were similar<a href="https://academic.oup.com/noa/article/3/1/vdab067/6279119" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. There is something in that argument. But three things have to be kept in mind alongside it.</p>
<p>First, the era. JO22506 was published in 2012; JG002 enrolled between 2016 and 2018. Several years sit between them, and supportive care, later-line drugs and the density of imaging follow-up all changed over that stretch. The same disease treated in a later era drifts upward in survival on its own, without anyone doing anything clever.</p>
<p>Second, the entry criteria are not identical. JG002's performance-status threshold was a little looser than JO22506's, but the median tumour volume it enrolled was only 7.3 millilitres, which is a fairly small lesion. People who make it into a BNCT trial have been through a screen: they are well enough to travel, well enough to lie still for the irradiation, and their disease is in a form the beam can reach. A selected group does better than an unselected one whatever you then give it.</p>
<p>Third, and this is the one that matters most: <strong>of JG002's 27 patients, 21 (78%) received bevacizumab after their disease progressed</strong>, and 5 of those also had temozolomide<a href="https://academic.oup.com/noa/article/3/1/vdab067/6279119" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>.</p>
<p>To say it in plain words: <strong>what this comparison actually contains is "BNCT followed by bevacizumab" set against "bevacizumab alone".</strong> Twenty-one of the twenty-seven treated patients went on to receive the very drug the comparison group had been given, so subtracting one survival figure from the other does not leave you with the effect of BNCT by itself. The original paper states this perfectly clearly, and it almost never survives into a second-hand account.</p>

<h4>Third thing: the price</h4>
<p>Treatment-related adverse events of grade 3 or higher occurred in 22 patients, which is 81.5%<a href="https://academic.oup.com/noa/article/3/1/vdab067/6279119" target="_blank" rel="noopener"><sup class="cit">[1]</sup></a>. Brain oedema 48.1%, of which grade 3 was 11.1%; alopecia 66.7%; raised amylase 81.5%, of which grade 3 or higher was 66.7% and grade 4 alone was 48.1%. Serious adverse events 33.3%.</p>
<p>This is not a gentle treatment. Any description of BNCT as a precise therapy with few side effects can be held up against this set of figures and read a second time. What these figures are doing here is keeping the survival numbers company, because a survival figure quoted without its toxicity figure is only half of what happened to those 27 people.</p>

<h4>The 2025 extended follow-up</h4>
<p>The same patients were later reported with longer follow-up: one-year survival still 79.2%, with a narrower confidence interval of 63.3 to 88.7, and median overall survival 19.2 months<a href="https://academic.oup.com/noa/article/7/Supplement_6/vdaf236.031/8380849" target="_blank" rel="noopener"><sup class="cit">[3]</sup></a>.</p>
<p>Note that this is a conference abstract, not a full journal paper; I could not obtain a journal version when I did my checking. The extended follow-up also carries a different confidence interval from the original report, so anyone quoting it has to say which of the two they are drawing on. That kind of care looks fussy from outside, and it is precisely where having read the original separates from having copied something second-hand.</p>

<h4>So does this treatment work</h4>
<p>Only one statement here holds up, and this is it: <strong>in a selected group of patients with recurrent glioblastoma, small tumours, and enough reserve to go on to further treatment, BNCT followed by bevacizumab appears to give longer survival than a historical cohort given bevacizumab alone.</strong> That is the strongest statement this data will support, and not one word can be added to it.</p>
<p>It is not a randomised trial, so we do not know how much of the gap came from BNCT, how much from the selection, and how much from the era. Answering that requires randomisation, and this field has still not produced any. That is a statement about the evidence, not about the treatment: an unanswered question is not the same as a negative answer, and it is not the same as a positive one either.</p>
<p>Take the method in this article away with you. Next time any treatment claims that survival went from X to Y, you have three questions ready: <strong>which year is the control group from? Were the entry criteria the same? And what else did the treated group go on to receive afterwards?</strong></p>""",
)
